FROM node:22-alpine AS frontend-dev

WORKDIR /app/admin-ui
COPY admin-ui/package.json admin-ui/pnpm-lock.yaml admin-ui/.npmrc admin-ui/pnpm-workspace.yaml ./
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
COPY admin-ui ./

CMD ["pnpm", "dev", "--host", "0.0.0.0", "--port", "5173"]

FROM frontend-dev AS frontend-builder

RUN pnpm build

FROM rust:1.92-bookworm

RUN cargo install cargo-watch --locked

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY --from=frontend-builder /app/admin-ui/dist /app/admin-ui/dist

RUN cargo fetch --locked

EXPOSE 8990

CMD ["cargo", "watch", "--poll", "--why", "--watch", "src", "--watch", "Cargo.toml", "--watch", "Cargo.lock", "-x", "run --no-default-features -- -c /app/config/config.json --credentials /app/config/credentials.json"]
